services:
  # Single Web Service for Both Backend and Frontend
  - type: web
    name: pitchine-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FRONTEND_URL
        value: "https://pitchine.com"
