services:
  # -----------------
  # Backend API Service
  # -----------------
  - type: web
    name: pitchine-api
    runtime: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5 # Or your specific Python version
      - key: FRONTEND_URL
        value: "https://pitchine.com"

  # ---------------------
  # Frontend Static Service
  # ---------------------
  - type: static
    name: pitchine-client
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: build
    # Rewrite rule for Single Page Applications
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pitchine-api
          property: url
